# Generated by Django 5.1.7 on 2025-04-11 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TallySession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plant')),
            ],
        ),
        migrations.CreateModel(
            name='WeightClassification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.TextField()),
                ('min_weight', models.FloatField()),
                ('max_weight', models.FloatField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_classes', to='api.plant')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('required_bags', models.FloatField()),
                ('allocated_bags', models.FloatField()),
                ('tally_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tallysession')),
                ('weight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weightclassification')),
            ],
        ),
    ]
