# Generated by Django 5.1.7 on 2025-04-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plant_tallysession_weightclassification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightclassification',
            name='category',
            field=models.TextField(choices=[('uncategorized', 'Uncategorized'), ('byproduct', 'Byproduct'), ('dressed', 'Dressed')], default='uncategorized'),
        ),
    ]
